catalogMode: prefer
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: false
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - cached-factory@0.1.0
  - '@babel/core@7.28.5'
  - semver@6.3.1

catalogs:
  dev:
    '@commitlint/cli': ^20.2.0
    '@commitlint/config-conventional': ^20.2.0
    '@eslint/config-inspector': ^1.4.2
    '@types/eslint-plugin-jsx-a11y': ^6.10.1
    '@types/node': ^25.0.3
    bumpp: ^10.3.2
    eslint-typegen: ^2.3.0
    lint-staged: ^16.2.7
    pnpm-workspace-yaml: ^1.4.3
    simple-git-hooks: ^2.13.1
    tsdown: ^0.18.3
    tsx: ^4.21.0
    typescript: ^5.9.3
    vitest: ^4.0.16
  inline:
    find-up-simple: ^1.0.1
  peer:
    '@eslint-react/eslint-plugin': ^2.4.0
    '@next/eslint-plugin-next': ^16.1.1
    '@prettier/plugin-xml': ^3.4.2
    '@react-native/eslint-plugin': ^0.83.1
    '@unocss/eslint-plugin': ^66.5.11
    eslint: ^9.39.2
    eslint-plugin-better-tailwindcss: ^3.8.0
    eslint-plugin-erasable-syntax-only: ^0.4.0
    eslint-plugin-format: ^1.1.0
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.26
    eslint-plugin-vue: ^10.6.2
    eslint-plugin-vuejs-accessibility: ^2.4.1
    eslint-processor-vue-blocks: ^2.0.0
    vue: ^3.5.26
    vue-eslint-parser: ^10.2.0
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@eslint/compat': ^2.0.0
    '@eslint/markdown': ^7.5.1
    '@stylistic/eslint-plugin': ^5.6.1
    '@typescript-eslint/eslint-plugin': ^8.50.1
    '@typescript-eslint/parser': ^8.50.1
    '@vitest/eslint-plugin': ^1.6.4
    eslint-config-flat-gitignore: ^2.1.0
    eslint-flat-config-utils: ^2.1.4
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-command: ^3.4.0
    eslint-plugin-import-lite: ^0.4.0
    eslint-plugin-jsdoc: ^61.5.0
    eslint-plugin-jsonc: ^2.21.0
    eslint-plugin-n: ^17.23.1
    eslint-plugin-no-only-tests: ^3.3.0
    eslint-plugin-perfectionist: ^5.1.0
    eslint-plugin-pnpm: ^1.4.3
    eslint-plugin-regexp: ^2.10.0
    eslint-plugin-toml: ^0.12.0
    eslint-plugin-unicorn: ^62.0.0
    eslint-plugin-unused-imports: ^4.3.0
    eslint-plugin-yml: ^1.19.1
    globals: ^16.5.0
    jsonc-eslint-parser: ^2.4.2
    local-pkg: ^1.1.2
    parse-gitignore: ^2.0.0
    toml-eslint-parser: ^0.10.1
    yaml-eslint-parser: ^1.3.2

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
