import type { OptionsConfig } from './types'

// @keep-sorted
export const CONFIG_PRESET_FULL_ON: OptionsConfig = {
  baseline: true,
  formatters: true,
  gitignore: true,
  imports: true,
  jsdoc: true,
  jsonc: true,
  jsx: {
    a11y: true,
  },
  markdown: true,
  nextjs: true,
  node: true,
  perfectionist: true,
  pnpm: true,
  react: true,
  regexp: true,
  sonarjs: true,
  stylistic: {
    experimental: true,
  },
  tailwindcss: { entryPoint: 'fixtures/stub.css' },
  test: true,
  toml: true,
  typescript: {
    erasableOnly: true,
    tsconfigPath: 'tsconfig.json',
  },
  unicorn: true,
  unocss: true,
  vue: {
    a11y: true,
  },
  yaml: true,
}

export const CONFIG_PRESET_FULL_OFF: OptionsConfig = {
  baseline: false,
  formatters: false,
  gitignore: false,
  imports: false,
  jsdoc: false,
  jsonc: false,
  jsx: false,
  markdown: false,
  nextjs: false,
  node: false,
  perfectionist: false,
  pnpm: false,
  react: false,
  regexp: false,
  sonarjs: false,
  stylistic: false,
  tailwindcss: false,
  test: false,
  toml: false,
  typescript: false,
  unicorn: false,
  unocss: false,
  vue: false,
  yaml: false,
}
