declare module '@next/eslint-plugin-next'
declare module 'eslint-plugin-jsx-a11y'
declare module 'eslint-plugin-effector'
declare module 'eslint-plugin-react-native'
declare module '@react-native/eslint-plugin'
declare module 'eslint-plugin-expo'
